
[versions]
accompanistPermissions = "0.30.1"
activityComposeVersion = "1.10.0"
agp = "8.7.3"
barcodeScanning = "17.3.0"
cameraCamera2Version = "1.4.1"
cameraCoreVersion = "1.4.1"
cameraLifecycleVersion = "1.4.1"
cameraViewVersion = "1.4.1"
coreKtxVersion = "1.15.0"
googleApiClientAndroidVersion = "1.34.0"
googleApiServicesSheetsVersion = "v4-rev305-1.25.0"
googleHttpClientGsonVersion = "1.42.3"
googleOauthClientAndroidVersion = "1.34.0"
gsonVersion = "2.10.1"
kotlinVersion = "2.0.0"
junitVersion = "4.13.2"
androidxJunitVersion = "1.2.1"
espressoCoreVersion = "3.6.1"
lifecycleRuntimeKtxVersion = "2.8.7"
composeBom = "2025.01.01"
composeCompiler = "1.5.1"
playServicesAuthVersion = "21.3.0"
runtimeLivedataVersion = "1.7.7"
coroutinesVersion = "1.6.4"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2Version" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCoreVersion" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycleVersion" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraViewVersion" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedataVersion" }
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroidVersion" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
google-api-services-sheets = { module = "com.google.apis:google-api-services-sheets", version.ref = "googleApiServicesSheetsVersion" }
google-http-client-gson = { module = "com.google.http-client:google-http-client-gson", version.ref = "googleHttpClientGsonVersion" }
google-oauth-client-android = { module = "com.google.oauth-client:google-oauth-client-android", version.ref = "googleOauthClientAndroidVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }

[bundles]
androidx-camera = ["androidx-camera-camera2", "androidx-camera-core", "androidx-camera-lifecycle", "androidx-camera-view"]